version: "3"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./services/influxdb:/var/lib/influxdb
    ports:
      - 9001:8086
    environment:
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
      INFLUXDB_READ_USER: "${INFLUXDB_READ_USER}"
      INFLUXDB_READ_USER_PASSWORD: "${INFLUXDB_READ_USER_PASSWORD}"
      INFLUXDB_WRITE_USER: "${INFLUXDB_WRITE_USER}"
      INFLUXDB_WRITE_USER_PASSWORD: "${INFLUXDB_WRITE_USER_PASSWORD}"
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
  grafana:
    image: grafana/grafana
    user: "104"
    ports:
      - 9000:3000    
    volumes:
      - ./services/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      GF_SERVER_ROOT_URL: "http://192.168.1.7:9000"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
